import os
import shutil

# Import the exact splits generated by main.py
from scripts.main import train_files, train_labels, val_files, val_labels, test_files, test_labels

def save_splits_locally(base_dir="dataset_splits"):
    # Dictionary mapping the split name to its files and labels
    splits = {
        "train": (train_files, train_labels),
        "val": (val_files, val_labels),
        "test": (test_files, test_labels)
    }
    
    # Dictionary mapping the binary label back to folder names
    classes = {0: "healthy", 1: "tumor"}
    
    print(f"Saving dataset splits to ..s/{base_dir}/ ...")
    
    for split_name, (files, labels) in splits.items():
        print(f"  -> Copying {len(files)} files for {split_name}...")
        
        # Create the subdirectories (e.g., dataset_splits/train/tumor)
        for cls_name in classes.values():
            os.makedirs(os.path.join(base_dir, split_name, cls_name), exist_ok=True)
            
        # Copy the files
        for file_path, label in zip(files, labels):
            cls_name = classes[label]
            dest_dir = os.path.join(base_dir, split_name, cls_name)
            filename = os.path.basename(file_path)
            dest_path = os.path.join(dest_dir, filename)
            
            shutil.copy2(file_path, dest_path)
            
    print("\n✓ Successfully saved all splits locally!")

if __name__ == "__main__":
    save_splits_locally()
